spring.application.name=user-service

spring.security.user.name = roshan
spring.security.user.password = roshan968

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://34.47.219.251:5432/userservice
spring.datasource.username=postgres
spring.datasource.password=roshan968
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration (Optional but commonly used with databases)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Port (if this is a web application)
server.port=8080

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web=DEBUG